### ISSUE TITLE
Create Scholarship & Internship Pages

### ISSUE THREAD

**Issue by maxellmilay** [upcsg-org/upcsg-website-v2#37]
# SUBTASKS
- [ ] Create new page named `scholarship-opportunities`

- [ ] Create new page named `internship-opportunities`

- [ ] Create a new component named `ScholarshipOpportunityCard.tsx`

![image](https://github.com/user-attachments/assets/e7bad278-2ffe-41b3-986c-90c23a4b499f)

- [ ] Create a new component named `InternshipOpportunityCard.tsx`

![image](https://github.com/user-attachments/assets/94c88adc-7cfc-4caa-8e2f-6708726a1dbd)

- [ ]  Integrate the new components into a grid for both pages

# Reference
## Scholarship Page
![image](https://github.com/user-attachments/assets/2ba00a77-db8f-45f0-87d7-9112bed93186)
## Internship Page
![image](https://github.com/user-attachments/assets/831074a5-a304-49dc-900d-46de822de669)
