### ISSUE TITLE
Create Officers Page

### ISSUE THREAD

**Issue by maxellmilay** [upcsg-org/upcsg-website-v2#38]
# Subtasks

- [ ] Create a new page named `officers`

- [ ] Create a new component `OfficerCard.tsx`

![image](https://github.com/user-attachments/assets/0d872538-07ca-43f5-9bf6-000a40f425ec)

- [ ] Integrate new component as a grid for the new page

# Reference
![image](https://github.com/user-attachments/assets/ee1c6fb8-b3cc-4f52-9501-ef3126b1c877)
