### ISSUE TITLE
Create Status Modals

### ISSUE THREAD

**Issue by maxellmilay** [upcsg-org/upcsg-website-v2#45]
# Subtasks

- [ ] Create Added to Shopping Bag Pop up

![image](https://github.com/user-attachments/assets/726e119b-0fbf-409b-8f99-97fa910db0d7)

- [ ] Create Added to Likes Pop up

![image](https://github.com/user-attachments/assets/30bc26ad-50fa-465a-80ba-c8c6d87cef84)

- [ ]  Create Submitted Successfully Pop up

![image](https://github.com/user-attachments/assets/7a4b4759-4ffd-4399-95e9-35488caf6ddf)

- [ ] Create Cancellation Confirmation Pop up

![image](https://github.com/user-attachments/assets/a12625cd-3f65-49b4-b9d1-314771f9bd85)
