### ISSUE TITLE
Create Bundles Page

### ISSUE THREAD

**Issue by maxellmilay** [upcsg-org/upcsg-website-v2#69]
# Subtasks:

- [ ] create new `/bundles` page
- [ ] create an advertisement panel within merch page that redirects to bundles page
- [ ] modularize components within the bundles page

Make sure to reuse the merch item interfaces and data since bundles are just groups of merch items
- [ ] create bundles interface
- [ ] create bundles mock data (group together merch items)

# Preview:
## Advertisement Panel for Bundles
![image](https://github.com/user-attachments/assets/21b71a3c-dfe7-4fbd-ae9e-2968c2ac86ac)
## Bundles Page
![image](https://github.com/user-attachments/assets/333f58bb-33b2-45ea-bc29-702d9595aee2)
